<?php
/**
 * @copyright Copyright 2021 Undefined.team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create Goip line' => 'Добавить Goip линию',
    'Alert time sms' => 'Время оповещения о sms',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот объект?',
    'Balance' => 'Баланс',
    'Balance pattern' => 'Шаблон баланса',
    'Check balance' => 'Проверка баланса',
    'Command' => 'Команда',
    'Command title' => 'Название команды',
    'Companion' => 'Компания',
    'Count lines' => 'Количество линий',
    'Create' => 'Создать',
    'Create device' => 'Добавить устройство',
    'Create lines' => 'Добавить линию',
    'Create message' => 'Создать сообщение',
    'Create operator' => 'Добавить оператора',
    'Create setting' => 'Добавить настройку',
    'Created at' => 'Создан',
    'Dashboard' => 'Рабочий стол',
    'Delete' => 'Удалить',
    'Device' => 'Устройство',
    'Devices' => 'Устройства',
    'Dial test' => 'Проверочный звонок',
    'Dial test number' => 'Номер проверочного звонка',
    'day' => 'день',
    'days' => 'дней',
    'hour' => 'час',
    'hours' => 'часов',
    'Duration' => 'Длительность',
    'Ended At' => 'Окончание',
    'Ever a {step}' => 'Каждый {step}',
    'Ever a {time} {step}' => 'Каждый {time} {step}',
    'Host' => 'IP адрес',
    'Port' => 'Порт',
    'ID' => 'ID',
    'Incoming' => 'Входищие',
    'Item ID' => 'ID объекта',
    'Last dial' => 'Последний звонок',
    'Last sms' => 'Последняя sms',
    'Line' => 'Линия',
    'Line ID' => 'ID линии',
    'Lines' => 'Линии',
    'Login' => 'Войти',
    'Messages' => 'Сообщения',
    'Name' => 'Имя',
    'Never' => 'Никогда',
    'Number' => 'Номер',
    'Operator' => 'Оператор',
    'Operators' => 'Операторы',
    'Outgoing' => 'Исходящее',
    'Password' => 'Пароль',
    'Phone Number' => 'Номер телефона',
    'Phone Number pattern' => 'Шаблон номера телефона',
    'Refresh' => 'Обновить',
    'Reset' => 'Сбросить',
    'Result' => 'Результат',
    'Result Pattern' => 'Шаблон результата',
    'Search' => 'Поиск',
    'Sent At' => 'Отправлоено',
    'Settings' => 'Настройки',
    'Status' => 'Статус',
    'Status message' => 'Сообщение статуса',
    'Text' => 'Текст',
    'The line number {number} is used.' => 'Линия номер {number} уже используется.',
    'Title' => 'Название',
    'Type' => 'Тип',
    'Update' => 'Редактировать',
    'Update {modelClass}: ' => 'Редактирование {modelClass}: ',
    'Value' => 'Значение',
    'Username' => 'Имя пользователя',
    'Subject' => 'Заголовок',
    'Body' => 'Текст сообщения',
    'Verification Code' => 'Код подтверждения',
    'Users' => 'Пользователи',
    'Setting permissions for' => 'Настройка прав для',
    'Check All' => 'Выбрать все',

    'Feedback' => 'Обратная связь',
    'Send' => 'Отправить',

    'If you have questions or requests, please fill out the following form to contact us. Thank you!' => 'Если у вас есть вопросы или пожелания, пожалуйста, заполните следующую форму, чтобы связаться с нами. Спасибо!',
    'Thank you for contacting us. Soon we will answer you.' => 'Благодарим Вас за обращение. Скоро мы Вам ответим.',

    'From' => 'От',
    'received' => 'получено',
    'Delete message?' => 'Удалить сообщение?',
    'Sign in' => 'Войти',
    'Sign up' => 'Регистрация',
    'Register' => 'Создать аккаунт',
    'Remember me' => 'Запомнить меня?',
    'Repeat password' => 'Повторите пароль',
    'This login is already taken' => 'Этот логин уже занят',

    'Bulk SMS sending' => 'Массовая отправка смс',
    'Select line' => 'Выберите линию',
    'List of numbers and messages' => 'Список номеров и сообщений',
    'Messages queued for sending!' => 'Сообщения поставлены в очередь на отправку!',

    'The requested page does not exist' => 'Запрашиваемая страница не существует',

    'Month' => 'Месяц',
    'Week' => 'Неделя',
    'Day' => 'День',
    'SMS was' => 'Смс была',
    'Call was' => 'Звонок был',

    'No sim card' => 'Нет sim карты',
    'Call' => 'Позвонить',
    'Reload module' => 'Перезагрузить модуль',

    'Deposit' => 'Пополнение баланса',
    'Deposit to' => 'Пополнение баланса',

    'Sum' => 'Сумма',
    'Close' => 'Закрыть',
    'Add' => 'Пополнить',
    'Send USSD' => 'Отправить USSD',
    'Send a call' => 'Отправить звонок',
    'Send SMS' => 'Отправить смс',

    'Convenient UI for your GoIP' => 'Удобный интерфейс для вашего GoIP',
    'Main' => 'Главная',
    'Scheme of work' => 'Схема работы',
    'Advantages' => 'Преимущества',
    'Only the most necessary functionality for receiving, sending messages and executing USSD commands.' => 'Только самые необходимые функции для получения, отправки сообщений и <br> выполнения команд USSD.',
    'Monitoring the balance and maintaining the SIM card in an active state makes the service more convenient.' => 'Контроль баланса и поддержание SIM-карты в активном состоянии делает услугу более удобной.',
    'To work with our system you will need:' => 'Для работы с нашей системой вам понадобится:',
    'Configure an external access to the GoIP' => 'Настроить внешний доступ к GoIP',
    'Connect to your GoIP through our service' => 'Подключиться к вашему GoIP через наш сервис',
    'Customize our service to your needs' => 'Настроить наш сервис в соответствии с вашими потребностями',
    'Get demo access' => 'Получить демо-доступ',
    'SIM card update' => 'Обновление SIM-карты',
    'Protection against blocking by the operator of the SIM card due to its non-use (no calls to other numbers).' => 'Защита от блокировки оператором SIM-карты из-за ее неиспользования (нет звонков на другие номера).',
    'Convenient monitoring' => 'Удобный мониторинг',
    'The interface allows you to track all SIM-cards at once, to see their balance and to understand for what purposes the SIM-card is used.' => 'Интерфейс позволяет отслеживать все SIM-карты одновременно, видеть их баланс и понимать, для каких целей используется SIM-карта.',
    'Fast message reception' => 'Быстрый прием сообщений',
    'Our service checks for new messages once every 1 minute. This way you will be able to receive messages fairly quickly.' => 'Наш сервис проверяет наличие новых сообщений раз в 1 минуту. Таким образом, вы сможете получать сообщения довольно быстро.',
    'Is it safe?' => 'Это безопасно?',
    'We use a secure data transfer protocol, all important data is stored and sent in an encrypted form.' => 'Мы используем безопасный протокол передачи данных, все важные данные хранятся и отправляются в зашифрованном виде.',
    'Where balance information is stored?' => 'Где хранится информация о балансе?',
    'Balance information is stored on our servers. The system automatically makes a request to the operator and keeps the balance information up to date.' => 'Информация о балансе хранится на наших серверах. Система автоматически отправляет запрос оператору и обновляет информацию о балансе.',
    'Will third parties be able to gain access to my data?' => 'Смогут ли третьи лица получить доступ к моим данным?',
    'No, we do not share nor sell our customer data and we protect it against leakage as much as possible.' => 'Нет, мы не передаем и не продаем данные наших клиентов и максимально защищаем их от утечки.',
    'I still have questions' => 'У меня все еще есть вопросы',
    'Write us an' => 'Напишите нам на',
    'and we will answer them!' => 'и мы ответим!',
    'All rights reserved' => 'Все права защищены',
    'Terms of Agreement' => 'Условия соглашения',
    'Terms of use' => 'Условия использования',
    'Get start' => 'Начать',
    'Last update' => 'Последнее обновление',
    'Rules was updated' => 'Права успешно обновлены',
    'Rule Settings' => 'Права доступа',
    'Account settings' => 'Настройки аккаунта',

    'IMS Validation Code' => 'Код подтверждения',
    'IMS connection added' => 'Подключение добавлено',

    'WrongDeviceCredentials' => 'Данные для подключения к устройству указаны неверно',

    'missing_line_title' => 'линия без названия',
    'missing_sim_card_phone' => 'нет сим-карты',

    'no_sim_card' => 'нет сим-карты',
    'messages_filter' => 'Фильтр для вывода сообщений',

    'matches at least one of conditions' => 'удовлетворяет хотя-бы одному из условий',
    'matches all the conditions' => 'удовлетворяет всем условиям',

    'messages_filters' => 'Фильтр для сообщений',

    'matches' => 'соответствует',
    'doesn\'t match' => 'не соответствует',
    'contains' => 'содержит',
    'doesn\'t contain' => 'не содержит',

    'сomparison_conditions' => 'Условия сравнения',
    'add_condition' => 'Добавить условие',
    'condition_field' => 'Поле',
    'condition_condition' => 'Условие',
    'condition_text' => 'Значение',

    'API access forbidden: User blocked.' => 'Пользователь заблокирован',

    'missing_line_number' => 'линия без номера',

    'Unknown number' => 'Номер неизвестен',
    'Untitled line' => 'Линия без названия',
    'missing phone number' => 'номер телефона не задан',

    '{0} device settings' => 'Настройки устройства {0}',
    'Display empty lines' => 'Отображать пустые слоты',
    'Device weight' => 'Вес устройства',

    '{0} device' => 'Устройство {0}',

    'Connection' => 'Подключение',
    'Display settings' => 'Настройки отображения',
    'Access/sharing settings' => 'Настройки доступа/расшаривания',
    'Reboot' => 'Перезагрузка',

    'Device settings' => 'Настройки устройства',

    'Device settings updated' => 'Настройки устройства обновлены',

    'Device {0} reboot' => 'Перезагрузка устройства {0}',
    'Reboot device' => 'Перезагрузить устройство',
    'Are you sure you want to reboot this device?' => 'Вы уверены, что хотите перезагрузить это устройство?',
    
    'Balance changes history' => 'История последних списаний',
    'Device {device_title}:' => 'Устройство {device_title}:',
    'Total: -{device_balance_diff}₽' => 'Итого: -{device_balance_diff}₽',

    'Line {number}' => 'Линия {number}',
];
